% -------------------------------------------------------------------------
% Script: extract_cbf_pvcorr_std.m
%
% 📌 Purpose:
% This script extracts mean cerebral blood flow (CBF) values from standard-space
% ASL outputs, specifically the `perfusion_calib.nii.gz` file generated by 
% FSL's oxford_asl with partial volume correction (PVC).
%
% 🧠 Context:
% This script is designed to be run *after* the ASL preprocessing pipeline
% (`asl_analysis.sh`) has completed for each subject and session.
% That pipeline performs motion/distortion correction, ASL calibration, and 
% quantification using `oxford_asl`, and saves the results in standard (MNI) 
% space under the path:
%
%   derivatives/asl_analysis/<sub>/<ses>/pld_all/std_space/pvcorr/
%
% 🗂️ Masks:
% This script uses a set of masks (aligned to MNI space) for:
%   - Whole-brain grey matter (GM)
%   - Frontal lobe
%   - Cingulate gyrus
%   - Motor cortex
%   - Occipital lobe
%   - Parietal lobe
%
% These masks should be stored in:
%   derivatives/ROI_masks/std_space/<sub>/<ses>/
%
% 📤 Output:
% The script saves a TSV summary of mean CBF values per region to:
%   derivatives/asl_analysis/<sub>/<ses>/cbf_summary_std.tsv
%
% ✅ Requirements:
% - All masks must be in standard (MNI) space and in NIfTI format
% - Requires the NIfTI Toolbox for MATLAB (Jimmy Shen)
%   https://www.mathworks.com/matlabcentral/fileexchange/8797-tools-for-nifti-and-analyze-image
%
% -------------------------------------------------------------------------


addpath('/path/to/NIfTI_toolbox'); % <<< CHANGE to your NIfTI toolbox path

sub = 'sub-0001';
ses = 'ses-02N';

root_dir = '/your/project/root';  % <<< CHANGE to your project root

cbf_file = fullfile(root_dir, 'derivatives', 'asl_analysis', sub, ses, ...
    'pld_all', 'std_space', 'pvcorr', 'perfusion_calib.nii.gz');

% Paths for GM and ROI masks
gm_mask_path = fullfile(root_dir, 'derivatives', 'asl_analysis', sub, ses, 'gm_mask_std.nii.gz');
roi_dir = fullfile(root_dir, 'derivatives', 'ROI_masks');

mask_files = {
    gm_mask_path,
    fullfile(roi_dir, 'frontal_roi_std.nii.gz'),
    fullfile(roi_dir, 'cingulate_roi_std.nii.gz'),
    fullfile(roi_dir, 'motor_roi_std.nii.gz'),
    fullfile(roi_dir, 'occipital_roi_std.nii.gz'),
    fullfile(roi_dir, 'parietal_roi_std.nii.gz')
};

region_names = {'GM', 'Frontal', 'Cingulate', 'Motor', 'Occipital', 'Parietal'};
mean_cbf = zeros(size(mask_files));

% Load CBF image
nii = load_nii(cbf_file);
cbf_img = double(nii.img);

for i = 1:length(mask_files)
    mask_nii = load_nii(mask_files{i});
    mask = logical(mask_nii.img);
    values = cbf_img(mask);
    values = values(values > 0);
    mean_cbf(i) = mean(values);
end

% Write TSV output
T = table(region_names', mean_cbf', 'VariableNames', {'Region', 'MeanCBF'});
out_path = fullfile(root_dir, 'derivatives', 'asl_analysis', sub, ses, 'cbf_summary_std.tsv');
writetable(T, out_path, 'FileType', 'text', 'Delimiter', '\t');

fprintf('✅ CBF summary saved to: %s\n', out_path);
